### ISSUE TITLE
Memory leaks in LambdaSummaryClass

### ISSUE THREAD

**Issue by meciarm** [wala/WALA#419] opened 2019-02-12 15:32 UTC
Hello, 
we have occured memory leaks probably produced by WALA.

We are using WALA 1.5.0 (via Maven) in JUnit tests. We are computing new ClassHierarchy and CallGraph in every unit test. 

In class LambdaSummaryClass, static field _summaries_ seems to collect and hold information about ClassHierarchy from each of previous runs (see attached pictures). 
![lambdasummaryclass](https://user-images.githubusercontent.com/5889064/52564929-aa657200-2e05-11e9-9a39-76bddfdb54eb.jpg)
![memory_before_test](https://user-images.githubusercontent.com/5889064/52564951-b8b38e00-2e05-11e9-81b3-e5ea786cac65.jpg)
![memory_after_test](https://user-images.githubusercontent.com/5889064/52564955-bc471500-2e05-11e9-9820-2b87444aa8e9.jpg)
This way, we have memory issues after running higher amount of JUnit tests. Same issue will probably arise in case, when several separate WALA analyses are done in sequence. 

Is there any fix available for solving our issue (expect of manually clearing summaries field via Reflection after each test)?

**Comment by msridhar** [comment] 2019-02-12 18:23
Thanks for the report, @meciarm.  I think we should get rid of this static field entirely and put the state inside the `AnalysisCache` or something like that.

In the meantime, due to use of `WeakHashMap` this should only be causing a leak if there is some strong reference from the `LambdaSummaryClass` values back to the `BootstrapMethod` keys.  In your memory profile view can you see if the `BootstrapMethod`s are reachable from the `ClassHierarchy` objects?  If so, we need a different scheme here.  But if not, this is not the root cause of the leak.

**Comment by rikiel** [comment] 2019-02-13 15:49
Hello, @msridhar 
There is a circle in references. `LambdaSummaryClass` holds reference to both `BootstrapMethod` (through reference to `SSAInvokeDynamicInstruction`) and to `ClassHierarchy`. And `ClassHierarchy` holds reference back to `LambdaSummaryClass`...

**Comment by msridhar** [comment] 2019-02-13 16:46
Ok, that's bad 😐 Let me look into a proper fix for this that will allow for a proper architecture moving forward.  If that takes too long I can just add a static `clear()` method but would rather not.

**Comment by msridhar** [comment] 2019-02-14 18:53
@meciarm I believe this leak is fixed.  Are you able to test using WALA master?  If it's helpful I could make a SNAPSHOT build for testing.

**Closed** 2019-02-14 18:52 UTC

**Comment by msridhar** [comment] 2019-02-14 20:21
@meciarm I created a `1.5.2-SNAPSHOT` build that you can use to test if the fix worked.  Please let us know.

**Comment by rikiel** [comment] 2019-02-15 10:49
@msridhar , thank you for the quick fix.
It works well, no `ClassHierarchy` classes stays stuck in memory between tests.
When do you plan to release `1.5.2` version?

**Comment by msridhar** [comment] 2019-02-17 17:10
@meciarm I can cut a 1.5.2 release soon.  Will let you know when it's done.

**Comment by msridhar** [comment] 2019-02-18 22:47
@meciarm 1.5.2 has been released

**Comment by meciarm** [comment] 2019-02-20 12:34
@msridhar I have done some additional testing with @rikiel and everything seems to work fine now. Thank you very much for fix.
