### ISSUE TITLE
Facing issue in updating the Debian package 

### ISSUE THREAD

**Issue by Manas-kashyap** [wala/WALA#774] opened 2020-05-16 16:07 UTC
Hello ,
I am Manas Kashyap an active Debian Contributor and currently working on wala, , while building we are getting a failure [https://paste.ubuntu.com/p/yY5pyNj6Bz/ (full log of the failure)] regarding core project . 
FAILURE: Build failed with an exception.

* Where:
Build file '/home/manas/build-package/wala/wala/build.gradle' line: 71

* What went wrong:
A problem occurred evaluating root project 'com.ibm.wala'.
> No signature of method: org.gradle.api.internal.tasks.RealizableTaskCollection.configureEach() is applicable for argument types: (build_36fvhi5na1es3p5chqxa3kufy$_run_closure2$_closure7) values: [build_36fvhi5na1es3p5chqxa3kufy$_run_closure2$_closure7@5613247e]

Small summary of the failure, the link to my repository is https://salsa.debian.org/Manas-kashyap-guest/wala 

How to reproduce the error or failure ?
Clone the repo and try to run debuild -b (after installing all the dependency listed in debian/control file)

**Comment by liblit** [comment] 2020-05-16 16:26
Thank you for that link to the complete build log: very helpful! Looking through that log, I see that you are building WALA 1.5.2 using Gradle 4.4.1. WALA generally adopts new Gradle releases fairly quickly, and Gradle 4.4.1 is surely too old to build WALA 1.5.2.

I recommend that you build WALA using its own bundled `gradlew` wrapper. You can always trust that WALA ships with a suitable version of Gradle to build itself. Conversely, I cannot offer any assurances that WALA will build with versions of Gradle newer or older than the one it ships with.

Does using the bundled `gradlew` solve your build problem?

**Comment by Manas-kashyap** [comment] 2020-05-17 12:05
Hi , so the issue is we cant use the gradlew of wala , rather in Debian we have to make it generic by installing it with the version of Gradle available in Debian. 
So, if you can think of someway to resolve it out ,  Kindly Let me know, Thank you

**Comment by liblit** [comment] 2020-05-17 12:55
> in Debian we have to make it generic by installing it with the version of Gradle available in Debian

If this is a general Debian policy, then what is the Debian-recommended approach when the standard Debian version of a build tool is too old to build the software being packaged? Presumably this does come up from time to time, not just for Gradle+WALA.

Looking at Gradle’s release history, I see that the Gradle 4.4.1 you are required to use was released on December 20, 2017. WALA picked up that version of `gradlew` on January 13, 2018. That might be a good starting point if you are searching for a WALA release old enough to build with Gradle 4.4.1. Newer versions of WALA might still build with Gradle 4.4.1 too, but (as you’ve already discovered) by the time you reach WALA 1.5.2 we’re no longer buildable using Gradle 4.4.1. Consider using `git bisect` to find the newest WALA that can still build with Gradle 4.4.1.

That being said, WALA’s Gradle build system took a long time to mature. For a years Maven was the official build system, with Gradle gradually catching up. Eventually Gradle worked well enough for us that Maven builds started to become less reliable and started to depend on Gradle setup steps. We committed to Gradle-only builds and started removing obsolete Maven build infrastructure in #618. I would say that after #618 it became impossible to build a WALA without Gradle. Before #618 that may still have worked, and the farther back in time you go before #618, the closer you’ll get to something that builds entirely using Maven.

If I had to guess, I’d say that the newest version of WALA that builds using Gradle 4.4.1 is probably so old that you’d be better off building it with Maven. And once you’re using Maven, you May as well systematically search for the newest WALA release that can still be built using Maven. That will definitely be some release made before #618, but I cannot say which specifically.

**Comment by msridhar** [comment] 2020-05-17 13:54
I'm also curious about this Debian policy regarding `gradlew`.  Is it ok for the Gradle build system to download 3rd-party libraries for the purposes of the build, or do those need to be part of the Debian installation as well?

In any case, @Manas-kashyap if you can find the most recent git SHA that still works with the Debian build (either building with Maven or Gradle), I am open to cutting some kind of maintenance release based on that git SHA for use with Debian.

**Comment by liblit** [comment] 2020-05-17 14:13
@msridhar asked:

> Is it ok for the Gradle build system to download 3rd-party libraries for the purposes of the build, or do those need to be part of the Debian installation as well? 

According to [Debian’s Java/Packaging/Gradle](https://wiki.debian.org/Java/Packaging/Gradle):

> You will have to patch the build.gradle file most of the time, to remove unneeded plugins or make the build system Debian compliant, e.g. prevent any downloads from the internet at build time and use system libraries instead.

Well, that’s going to be exciting for WALA, which generally wants to download gigabytes of stuff at build time because a cautious IBM lawyer once said so.

But apparently [Debian does currently package WALA 1.5.1](https://tracker.debian.org/pkg/wala)? I’m actually baffled as to how that’s even possible given the disparities between Debian’s packaging policies and WALA’s build system.

To be clear, I understand the risks of bundling multiple copies of dependencies with various packages, and I am a big fan of strictly hermetic builds. But for WALA, that’s just very far away from how it’s currently done.

**Comment by msridhar** [comment] 2020-05-17 14:17
Yes, that could be a big pain.  I think WALA's main required compile/runtime dependencies are much smaller than the dependencies needed for tests (also hard to add runtime dependencies due to lawyers 😄), so that might be what makes the tweaks for the Debian build possible.

**Comment by Manas-kashyap** [comment] 2020-05-17 14:41
Well really its a big pain to resolve things in gradle for this new version , and currently i am facing an issue https://paste.ubuntu.com/p/25g2vPR67S/ , if someone has any idea resolving this plugin issue it would be great.

**Comment by Manas-kashyap** [comment] 2020-05-17 14:57
Just asking if I remove all the test folder from that, will it still run the tests?

**Comment by liblit** [comment] 2020-05-17 16:30
@Manas-kashyap asked:

> Just asking if I remove all the test folder from that, will it still run the tests?

This sounds like a promising idea. Start by commenting out `com.ibm.wala.cast.test` where it appears in `settings.gradle`. Several other subprojects depend on `com.ibm.wala.cast.test` and therefore will start failing. Comment those out in `settings.gradle` too. Hopefully you will find that all of the subprojects you need to comment out in this way are test-related subprojects. By the time you’re done you should have a pruned WALA that still builds all of the main libraries but just omits many of those libraries’ tests.

While you are doing this, watch out for any cases where non-test-related subprojects start failing. We’ll need to take a closer look at those individually, if there are any.

**Comment by Manas-kashyap** [comment] 2020-05-17 17:11
Sure , Thank you so much

**Comment by Manas-kashyap** [comment] 2020-05-18 14:49
https://paste.ubuntu.com/p/hfKQtSYBgt/ hello mentors , any idea about this error i am facing after disabling test.

**Comment by Manas-kashyap** [comment] 2020-05-18 16:29
https://paste.ubuntu.com/p/knsHHvXHs6/ 

Heya guys so this is the final failure i think if i can patch it out i am all set for the package. 
Any idea on resolving it @msridhar @liblit

**Comment by msridhar** [comment] 2020-05-18 17:21
I can't reproduce this one locally, after checking out `R_1.5.2`.  I'm compiling with the `javac` that comes with this Java version:

```bash
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

@Manas-kashyap what is your Java version?

**Comment by Manas-kashyap** [comment] 2020-05-19 05:09
To reproduce the same error , 
https://salsa.debian.org/Manas-kashyap-guest/wala clone this repo and try to run debuild -b after installing the required dependency listed in Debian/control . 
I am using openJDK8 @msridhar

**Comment by msridhar** [comment] 2020-05-19 14:31
I presume this has to run on Linux?  Sorry I don't have a Linux machine readily available.  I could probably find a shell somewhere, but I won't have time to look at this myself in the immediate future.

**Comment by liblit** [comment] 2020-05-20 01:19
I did the following:

1. Spin up a Debian 10 virtual machine.
1. `pkcon install git`.
1. `git clone https://salsa.debian.org/Manas-kashyap-guest/wala`
1. `cd wala`
1. install all dependencies listed in `debian/control`
    * for the dependency that is listed as `default-jdk-headless (>= 2:1.8) | default-jdk (>= 2:1.8)`, install `default-jdk-headless`
1. `debuild -b`

The `debuild` command failed, but not in the same place that @Manas-kashyap reported. The informative part of the build output was:

```
javadoc: error - Error fetching URL: file:/usr/share/doc/default-jdk/api/
```

I see no `/usr/share/doc/default-jdk/api/` directory on my Debian 10 system, but I do see both `/usr/share/doc/default-jdk-doc/api/` and `/usr/share/doc/default-jdk-headless/api/`. After running `sudo apt-get install default-jdk`, I find that a `/usr/share/doc/default-jdk/api/` directory has appeared. So the part of the `debian/control` file that called for `default-jdk-headless (>= 2:1.8) | default-jdk (>= 2:1.8)` seems wrong: it had to be `default-jdk`, not `default-jdk-headless`. This is probably a defect in Debian-specific build tweaks, because WALA's build scripts never explicitly mention `/usr/share/doc/default-jdk*/api/` at all.

I run `debuild -b` again. It fails again, now reporting:

```
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
```

The code being documented does not use modules, as far as I am aware. The whole WALA code base uses JDK 8, which predates modules. I don't know why `javadoc` thinks modules are being used. Unfortunately I just don't know much about modules at all, really. Perhaps the build would go better if it were using a Java 8 `javadoc` rather than the Java 11 `javadoc` which seems to be the default? And I'm definitely skeptical that WALA will compile properly using a Java 11 `javac`, running in a Java 11 JVM. WALA has been lingering at Java 8 for quite some time, and I'm pretty sure it doesn't all just work if moved up to a Java 11 environment.

**Comment by msridhar** [comment] 2020-05-20 01:24
Thanks so much for the investigation @liblit!  I agree 100% that building WALA with JDK 11 is _not_ supported at the moment, and certainly not supported with release 1.5.2.  Creating a useful WALA distribution will require building with JDK 8.

**Comment by Manas-kashyap** [comment] 2020-05-20 04:34
Thank you so much @msridhar @liblit , now i know how to work and patch things out , Thanks

**Comment by msridhar** [comment] 2020-05-20 05:16
Great! Shall we close this issue then @Manas-kashyap?

**Comment by Manas-kashyap** [comment] 2020-05-20 05:17
No , lemme finish it up and once we have wala in Debian again , we are all good to close it up.

**Comment by Manas-kashyap** [comment] 2020-05-26 15:18
@liblit @msridhar i think now you can close this issue as i finally managed to build 1.5.2 version of wala with the pre existing gradle in Debian , and hope soon it will be in Debian archive for everyone to use. 
Thank you so much Guys.

**Comment by msridhar** [comment] 2020-05-26 15:23
Great news, thanks @Manas-kashyap!

**Closed by msridhar** 2020-05-26 15:23 UTC
Labels: gradle

**Comment by liblit** [comment] 2020-05-26 16:04
Hooray!

**Comment by Manas-kashyap** [comment] 2020-05-27 06:32
https://tracker.debian.org/news/1147694/accepted-wala-152-1-source-into-unstable/ @msridhar @liblit .
