### ISSUE TITLE
Can't generate call graph successfully when I exclude java/lang/.*(except java/lang/Object). Besides java/lang/Object, is there any class indispensable for call graph construction?

### ISSUE THREAD

**Issue by QRXqrx** [wala/WALA#611] opened 2019-12-14 02:26 UTC
![image](https://user-images.githubusercontent.com/49576982/70842247-26807a00-1e5c-11ea-9d66-6d4ecad3c587.png)
![image](https://user-images.githubusercontent.com/49576982/70842250-3ac47700-1e5c-11ea-9508-6cd13063a280.png)

**Comment by QRXqrx** [comment] 2019-12-14 02:28
When I stop exclude java/lang/.*, the construction of call graph runs normal!

**Comment by msridhar** [comment] 2019-12-14 20:09
Duplicate of #285

**Comment by QRXqrx** [comment] 2019-12-19 12:50
> Duplicate of #285

Hmm... I still cannot generate call graph normally using 1.5.5-SNAPSHOT. Here's the exception information I got:
```
unexpected non-invokedynamic instruction!
instruction type: class com.ibm.wala.classLoader.JavaLanguage$JavaInstructionFactory$12
call site: invokestatic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeWorldClinit()V >@0
caller: Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere

java.lang.RuntimeException: unexpected non-invokedynamic instruction!

	at com.ibm.wala.ipa.summaries.LambdaMethodTargetSelector.getCalleeTarget(LambdaMethodTargetSelector.java:72)
	at com.ibm.wala.ipa.summaries.BypassMethodTargetSelector.getCalleeTarget(BypassMethodTargetSelector.java:139)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.getTargetForCall(PropagationCallGraphBuilder.java:693)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.lambda$getTargetsForCall$0(SSAPropagationCallGraphBuilder.java:2116)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec.rec(SSAPropagationCallGraphBuilder.java:541)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.iterateCrossProduct(SSAPropagationCallGraphBuilder.java:2097)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetsForCall(SSAPropagationCallGraphBuilder.java:2121)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(SSAPropagationCallGraphBuilder.java:1182)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(SSAPropagationCallGraphBuilder.java:1138)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(SSAInvokeInstruction.java:94)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(SSAPropagationCallGraphBuilder.java:272)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(SSAPropagationCallGraphBuilder.java:249)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(SSAPropagationCallGraphBuilder.java:225)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(SSAPropagationCallGraphBuilder.java:190)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(PropagationCallGraphBuilder.java:311)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(StandardSolver.java:56)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:251)
	at NewWALATest.printCallGraph(NewWALATest.java:45)
	at NewWALATest.test0(NewWALATest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```
Maybe I exclude too much class? Here's the exclusion file:
```
java\/awt\/.*
javax\/swing\/.*
javax\/.*
oracle\/.*
sun\/awt\/.*
sun\/swing\/.*
com\/sun\/.*
com\/oracle\/.*
org\/apache\/.*
sun\/.*
org\/netbeans\/.*
org\/eclipse\/.*
org\/openide\/.*
com\/ibm\/crypto\/.*
com\/ibm\/security\/.*
org\/apache\/xerces\/.*
dalvik\/.*
java\/io\/ObjectStreamClass*
apple\/.*
com\/apple\/.*
jdk\/.*
org\/omg\/.*
org\/w3c\/.*
com\/jrockit\/.*
javafx\/.*

([a-b]|[d-i]|[k-z]).*

javassist\/.*
junit\/.*
ch\/.*

com\/[A-Z].*
com\/([a-d]|[f-z]).*

java\/([a-k]|[m-z]).*
java\/lang\/([A-N]|[P-Z]|[a-z]).*
java\/lang\/O(a|[c-z]).*
```

And here's the class information I got:
```
Lcom/example/demo/Demo1ApplicationTests2
Lcom/example/demo/Service/AddressService
Lcom/example/demo/Controller/EmployeeController
Lcom/example/demo/Model/Address
Lcom/example/demo/AddressRepositoryTest
Lcom/example/demo/Model/Employee
Lcom/example/demo/Service/EmployeeService
Ljava/lang/Object
Lcom/example/demo/Repository/AddressRepository
Lcom/example/demo/Demo1ApplicationTests
Lcom/example/demo/EmployeeRepositoryTest
Lcom/example/demo/Demo1Application
Lcom/example/demo/Repository/EmployeeRepository
```

Does it mean that I should never exclude any class under `java/lang` when construct a call graph? I have make several trials by include `java/lang/Class.*` (which is indispensable in bytecode transformation according to JVM literature) and  `java/lang/String` (which is parameter of method), but the same exception information still occurs.

**Comment by msridhar** [comment] 2019-12-19 15:40
Hrm that is a strange crash stack. I would say it’s a bad idea to exclude the `java.lang` classes. Do you have a strong reason for doing so? Since it’s quite rare to do that, fixing this crash will be low priority I think.

**Comment by QRXqrx** [comment] 2019-12-20 00:30
> Hrm that is a strange crash stack. I would say it’s a bad idea to exclude the `java.lang` classes. Do you have a strong reason for doing so? Since it’s quite rare to do that, fixing this crash will be low priority I think.

Well, I do have a reason...but I have to admit the reason is not that crutial, too. In this part, all I want is the call relations within the object program, so I want a call graph as precise as possible. That's my thought at first. After meeting the stack above, I made another try by including lang classes, and then I find I can make it through that way. So feel free to fix other errors of more importance. 
Futhermore, I'm still curious about the **indispensability of lang classes**, could you please explain me the reason about that at your convinience? Thanks a lot. :-)

**Comment by msridhar** [comment] 2019-12-20 19:03
@QRXqrx the main explicit requirement related to `java.lang` is that any `ClassHierarchy` must have a root type, which for Java is `java.lang.Object`.  Regarding this crash, the [`java.lang.invoke` package](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/package-summary.html) is highly involved in support of Java 8 lambdas.  So I am not surprised that excluding those classes causes problems.  We should document that requirement.

Beyond that, I don't immediately know of reliance on the presence of `java.lang` classes, but I wouldn't be surprised if things break in certain cases.  E.g., there is a lot of code that reasons about `java.lang.String` and may not be robust to excluding it.

For your scenario, one thing you can do is filter the `CallGraph` after it is constructed.  E.g., see https://github.com/wala/WALA/blob/master/com.ibm.wala.util/src/com/ibm/wala/util/graph/EdgeFilteredNumberedGraph.java

**Comment by QRXqrx** [comment] 2019-12-21 03:23
@msridhar Thanks, that does help. BTW, can WALA analyse `field`? I mean the object initiated out of methods, like this:
```
	@Autowired
//	private EmployeeService empserv;
	public EmployeeService empserv;

	@Test
	public void test1() {
		Employee emp = new Employee(1111,"sdf");

		empserv.save(emp);
//
//		Employee emp3 = new Employee(123, "sdasd");
//		EmployeeService empserv1 = new EmployeeService();
//		empserv1.save(emp3);
//		Employee emp4 = empserv1.findOne(emp3.getId());
//
		Employee emp2 = empserv.findOne(emp.getId());
		assertNotNull(emp2);
		assertEquals("sdf",emp2.getName());
		assertEquals(1,empserv.findall().size());
	}
```
I didn't see information relate to `empserv` in the call graph result I got. However, if I initiate a `empsev1`  inside `test1()`, I can see corresponding result as expected. Is field object analyzed somewhere else?

**Comment by msridhar** [comment] 2019-12-22 02:43
Most call graph construction algorithms in WALA are based on pointer analysis and tracking the flow of objects in the program.  If such a technique does not observe any objects written into `empserv` then it will not find any call targets when `empserv` is used as a receiver.  You can use `CHACallGraph` to just build a call graph based on the class hierarchy, but this may be less precise.

**Comment by msridhar** [comment] 2019-12-22 16:32
I am going to close this issue as I think we answered the original question.  If there are specific bugs to report please open a new issue

**Closed by msridhar** 2019-12-22 16:32 UTC
