### ISSUE TITLE
Performance issue due to lots of ShrikeClass instantiations 

### ISSUE THREAD

**Issue by challe535** [wala/WALA#1069] opened 2021-12-01 17:59 UTC
I encountered a performance problem when creating a new ClassHierarchy. After profiling it seems the issue stems from tons instantiations of ShrikeClass objects in the ClassLoaderImpl.loadAllClasses() method. Profiling also showed a spike in garbage collection when this happens. For these reasons I suspect that the instantiation of ShrikeClass stored in tmpKlass is the cause of the performance issues. The temporary variable is only used to check an equality and thereafter the ShrikeClass object is discarded which could probably be replaced with a method call instead that performs the same function without instantiating any new objects.

The relevant code is:
~~~java
ShrikeClass tmpKlass = new ShrikeClass(reader, this, cha);
  if (tmpKlass.getReference().getName().equals(T)) {
    // always used the reader based on the entry after this point,
    // so we can null out and re-read class file contents
    loadedClasses.put(T, new ShrikeClass(entryReader, this, cha));
    if (DEBUG_LEVEL > 1) {
      System.err.println("put " + T + ' ');
    }
  } else {
    Warnings.add(InvalidClassFile.create(className));
  }
~~~

Specifically the first two lines seem to be the issue.

**Comment by msridhar** [comment] 2021-12-03 00:23
I wouldn't expect this to cause a big performance problem except maybe with a small heap.  How big is your heap size?  Can you share profiler data showing that this is in fact the root cause of the performance problem?

**Comment by msridhar** [comment] 2021-12-15 18:20
I'm going to close this as we can't make changes without more evidence.  Please comment if you still see this issue and have more data on the root cause

**Closed by msridhar** 2021-12-15 18:20 UTC
