### ISSUE TITLE
runtime of backward slice issue

### ISSUE THREAD

**Issue by quizzo** [wala/WALA#86] opened 2015-08-03 17:27 UTC
Per Manu's request (https://groups.google.com/forum/#!topic/wala-sourceforge-net/UvmrWews4CM)

I have noticed that backward slice is much slower than forward slice.
I ran forward and backward slice on 5 pretty small applications (about 50LOC, each)
and got the following results

FW 3.112s  vs. BW 5.242s
FW 12.594s vs. BW 49.808s
FW 12.338s vs. 50.007s
```
SDG sdg = new SDG(cg, pointer, ModRef.make(), 
                              DataDependenceOptions.NO_BASE_PTRS,ControlDependenceOptions.FULL);
```
finding the statement for slice
``` 
public static Statement findGeneric(CGNode n, java.lang.Class nodeType, Location loc) {
        IR ir = n.getIR();
        SSAInstruction[] insts = ir.getInstructions();
        if(loc == Location.FIRST){
            for (int i=0; i<insts.length; i++) {
                SSAInstruction s = insts[i];
                if (nodeType.isInstance(s)) {
                    return new NormalStatement(n, i);
                }
            }
        }
        else{
            for (int i=insts.length-1; i>=0; i--) {
                SSAInstruction s = insts[i];
                if (nodeType.isInstance(s)) {
                	
                    return new NormalStatement(n, i);
                }
            }
        }
        return null;
    }
```
FW stmt: ```Statement s_src = findGeneric(mainNode, SSANewInstruction.class, Location.FIRST);```
another option is to use the ```readLine``` using the findCallTo method (as suggested in the wala docs)
BW stmt: ```Statement s_sink = findGeneric(mainNode,  SSAReturnInstruction.class, Location.LAST);```

slicing 		
```Collection<Statement> slice_back = Slicer.computeBackwardSlice(sdg, s_sink);```
```Collection<Statement> slice_forward = Slicer.computeForwardSlice(sdg, s_src);```

I also tried the example code for ```findCallTo``` instead of my code for findGeneric, and got the same results.

Toy java app:
```
public class Sorting1 {
    public static void main(String[] args) {        
        ArrayList<Integer> arraySimple = new ArrayList<Integer>();
        BufferedReader in = null;
        String line = "";
        try {
            in = new BufferedReader(new FileReader("input.txt"));
            while ((line = in.readLine()) != null) {
                try{
                    Integer i = Integer.parseInt(line);
                    arraySimple.add(i);
                }catch(Exception e1){
                    // do nothing
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (in != null) {
                try {
                    in.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        
        int size = arraySimple.size();
        int temp;
        
        for(int i =0; i < size; i++){
            for(int j =0; j<size-1; j++){
                if(arraySimple.get(j) < arraySimple.get(j+1)){
                    temp = arraySimple.get(j);
                    arraySimple.set(j, arraySimple.get(j+1));
                    arraySimple.set(j+1, temp);
                }
            }
        }
        System.out.println(arraySimple);
    }

}
```

exclusion file:

```
java\/awt\/.*
java\/crypto\/.*
java\/security\/.*
java\/util\/.*
javax\/swing\/.*
javax\/crypto\/.*
javax\/util\/.*
sun\/awt\/.*
sun\/swing\/.*
com\/sun\/.*
sun\/.*
com\/oracle\/.*
oracle\/.*
org\/netbeans\/.*
org\/openide\/.*
com\/ibm\/crypto\/.*
com\/ibm\/security\/.*
org\/apache\/xerces\/.*
dalvik\/.*
apple\/.*
com\/apple\/.*
jdk\/.*
org\/omg\/.*
org\/w3c\/.*
```

**Comment by msridhar** [comment] 2015-08-06 15:44
Which exact source and sink statements were used to produce these results?

FW 12.594s vs. BW 49.808s
FW 12.338s vs. 50.007s

And can you confirm that the forward and backward slices were roughly the same size in these cases?

**Comment by quizzo** [comment] 2015-08-06 15:53
FW stmt: Statement s_src = findGeneric(mainNode, SSANewInstruction.class, Location.FIRST);
another option is to use the readLine using the findCallTo method (as suggested in the wala docs)
BW stmt: Statement s_sink = findGeneric(mainNode, SSAReturnInstruction.class, Location.LAST);

Would you like me to run these again and upload the times I am getting?
How would I check that the backward/forward are the same size? I am looking at my output and they do look about the same size, but if there is a better way to check please let me know.

**Comment by quizzo** [comment] 2015-08-06 16:00
For runtime:
just ran sorting code with the following statements and got the following times:

       CFG creation: 6.711 s
      Foward slice: 13.815 s
   Backwards slice: 50.707 s
        for forward I tried with both
		```Statement s_src = findGeneric(mainNode, SSANewInstruction.class, Location.FIRST);```

               and 
```		Statement s_src2 = findCallTo(mainNode, "readLine", SliceType.FORWARD);```

for backward
      ```  Statement s_sink2 = findGeneric(mainNode,  SSAReturnInstruction.class, Location.LAST);
	Collection<Statement> slice_back = Slicer.computeBackwardSlice(sdg, s_sink2 );```

**Comment by msridhar** [comment] 2015-08-06 18:38
I can't reproduce the slow backward slice on WALA master.  Can you pull the latest code and re-confirm?  And also can you report `slice_back.size()` for the backward slice?  For forward slice, I get a slice size of 11338 (slicing from the readLine call).  For backward slice, I get a slice size of 6941, and it actually runs faster.

**Comment by quizzo** [comment] 2015-08-06 18:44
forwards slicing...
size of forward:22770
backwards slicing...
size of back:47594

I will try to pull and see if this changes anything

**Comment by msridhar** [comment] 2015-08-06 18:45
Which JDK library version are you analyzing?

On Thu, Aug 6, 2015, 11:44 AM quizzo <notifications@github.com> wrote:

> forwards slicing...
> size of forward:22770
> backwards slicing...
> size of back:47594
>
> I will try to pull and see if this changes anything
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wala/WALA/issues/86#issuecomment-128471081>.
>
-- 
--Manu

**Comment by quizzo** [comment] 2015-08-06 18:49
java_runtime_dir =C:/Program Files/Java/jre7/lib/

**Comment by quizzo** [comment] 2015-08-06 18:50
After a pull 
forwards slicing...
size of forward:22770
backwards slicing...
size of back:47594
#########################
Timing:
      CFG creation: 2.356 s
      Foward slice: 23.077 s
   Backwards slice: 62.677 s

**Comment by msridhar** [comment] 2015-08-06 18:56
Ok.  Fundamentally, the only way forward and backward slicing differ at an implementation level is [right here](https://github.com/wala/WALA/blob/13a46d8ea3d0df13842ef53ea30ea839f9eb3cc0/com.ibm.wala.core/src/com/ibm/wala/ipa/slicer/Slicer.java#L252), where we use a [`BackwardsSupergraph`](https://github.com/wala/WALA/blob/13a46d8ea3d0df13842ef53ea30ea839f9eb3cc0/com.ibm.wala.core/src/com/ibm/wala/dataflow/IFDS/BackwardsSupergraph.java) for a backward slice.  The `BackwardsSupergraph` is just a thin indirection layer that reverses the direction of supergraph edges.  So, I don't think there is a bug here; it's just that the backwards slicing process is analyzing more code.  To get an idea of how much work is being done, you can pass this VM argument:

    -Dcom.ibm.wala.fixedpoint.impl.verbose=true

You should get some output on how many steps the fixpoint computation is taking.

Let me know if there is any evidence of a real performance bug in the code somewhere.

**Comment by quizzo** [comment] 2015-08-06 19:29
Is there anything in specific I am looking for in the Tabulation Solver prints to the console?

**Comment by quizzo** [comment] 2015-08-06 19:32
the forward started with 1000 and ended in 343000
the backward started with 1000 and ended in 949000

**Comment by Ido-Efrati** [comment] 2015-08-06 19:36
In addition, I tried to add java\/lang\/Throwable\/.* to the exclusion file (since I saw a lot of 
```  <HEAP_RET_CALLEE:Node: < Primordial, Ljava/lang/Throwable, printStackTrace(Ljava/lang/Throwable$PrintStreamOrWriter;)V > Context: Everywhere [[<Primordial,[B>][]],0> -> <HEAP_RET_CALLER:Node: < Primordial, Ljava/lang/Throwable, printStackTrace(Ljava/lang/Throwable$PrintStreamOrWriter;)V > Context: Everywhere [[<Primordial,Ljava/lang/OutOfMemoryError>],< Primordial, Ljava/lang/Throwable, backtrace, <Primordial,Ljava/lang/Object> >] call:invokevirtual < Primordial, Ljava/lang/Throwable$PrintStreamOrWriter, println(Ljava/lang/Object;)V > 2,26 @84 exception:27,0>
```
but even with this exclusion, I still see them. Why is this?

**Comment by quizzo** [comment] 2015-08-06 20:06
In addition, I tried to add java\/lang\/Throwable\/.* to the exclusion file (since I saw a lot of 
``` Context: Everywhere [[][]],0> -> Context: Everywhere [[],< Primordial, Ljava/lang/Throwable, backtrace, >] call:invokevirtual < Primordial, Ljava/lang/Throwable$PrintStreamOrWriter, println(Ljava/lang/Object;)V > 2,26 @84 exception:27,0>

but even with this exclusion, I still see them. Why is this?

**Comment by msridhar** [comment] 2015-08-06 20:17
I don't think your exclusion will catch the `Throwable$PrintStreamOrWriter`; maybe just write it explicitly?

In any case, the verbose output from the solver indicates that the backwards slicer is running almost 3 times as many fix point iterations as the forward slicer, which roughly corresponds to the difference in running time.  So I'm going to close this issue.

**Closed by msridhar** 2015-08-06 20:17 UTC

**Comment by quizzo** [comment] 2015-08-06 20:19
Thank you for the update. One last question, can you think of a reason the backward has almost 3 times more fix points?

**Comment by msridhar** [comment] 2015-08-06 20:24
It's hard to tell; a ton of library code is being analyzed.  It's either
that simply more code is relevant, or that the backward slice hits upon
some analysis imprecision that causes more code to be pulled in.

On Thu, Aug 6, 2015 at 1:19 PM quizzo <notifications@github.com> wrote:

> Thank you for the update. One last question, can you think of a reason the
> backward has almost 3 times more fix points?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wala/WALA/issues/86#issuecomment-128495814>.
>
-- 
--Manu
