### ISSUE TITLE
Ecliplse import issue

### ISSUE THREAD

**Issue by bowenshen** [wala/WALA#937] opened 2021-09-03 20:14 UTC
Hello Everyone

I successfully imported WALA several months before. But I met a issue now when I redo my steps.
I followed the instructions on https://github.com/wala/WALA/blob/master/README-Gradle.md#eclipse
I got pure WALA from github and installed required plugin of Eclipse.
Since I have multiple java version (sdkman management), gradle is setting to Java 11.0.2-open by default.
After importing, I tried to build project. There are 7 errors suck like
"Abstract methods do not specify a body"
"Illegal modifier for the interface method GetT; only public, abstract, default, static and strictfp are permitted"
"The type ReturnArray must implement the inherited abstract method PrivateInterface.GetT(Object)"
"build.properties does not exist" errors showing in	com.ibm.wala.core, com.ibm.wala.shrike, com.ibm.wala.util

I believe it might be related with Java version. So I switched back to import option and chose java 8.0.232-open instead. Several errors disappeared but 3 remained.
"build.properties does not exist" errors showing in	com.ibm.wala.core, com.ibm.wala.shrike, com.ibm.wala.util

Could you please help to resolve the issue?

The reason I need to build WALA myself instead of using WALA-start because I want to adding something in the source code for some specific purposes.

Thank you in advance

**Comment by msridhar** [comment] 2021-09-03 20:16
@bowenshen could you share the version of Eclipse you are using?

@liblit any ideas here?  I think you might have the most Eclipse setup expertise right now

**Comment by bowenshen** [comment] 2021-09-04 02:03
Thank you for reply. I'm using Eclipse IDE for Java Developers 2019-12 (4.14.0)

**Comment by liblit** [comment] 2021-09-05 00:35
I have not used Eclipse for WALA development for quite a few years. I don't think any of the WALA maintainers use Eclipse, so I'm not surprised that some regressions have slipped in. That being said, I think that I can speak on behalf of my fellow maintainers when I say that we would *like* WALA + Eclipse to be a working combination. So thank you for bringing these import problems to our attention, @bowenshen.

I've imported WALA into Eclipse 2021-06 (4.20.0). That Eclipse installation has Buildship 3.1.5.v20210113-0929 installed. My Eclipse is configured to know about Java 1.8, 11, and 16 SDKs, with Java 16 being the default. After import, the Problems view reports two warnings and two infos, neither of which I'm going to worry about for now. The Problems view also reports the following three errors:

| Description | Location |
|---|---|
| Abstract methods do not specify a body | https://github.com/wala/WALA/blob/af4b6c8fee8b0581d8184239ce825bce47e53ebe/com.ibm.wala.core/src/test11Subjects/java/privateInterfaceMethods/PrivateInterface.java#L8 |
| Illegal modifier for the interface method GetT; only public, abstract, default, static and strictfp are permitted | https://github.com/wala/WALA/blob/af4b6c8fee8b0581d8184239ce825bce47e53ebe/com.ibm.wala.core/src/test11Subjects/java/privateInterfaceMethods/PrivateInterface.java#L8 |
| The type ReturnArray must implement the inherited abstract method PrivateInterface.GetT(Object) | https://github.com/wala/WALA/blob/af4b6c8fee8b0581d8184239ce825bce47e53ebe/com.ibm.wala.core/src/test11Subjects/java/privateInterfaceMethods/TestArrayReturn/ReturnArray.java#L5 |

The first two errors above appear on the same line in a test subject that declares a `private` `interface` method. That feature was added to Java 9, so it makes sense that this source file is in the `test11Subjects` Gradle `SourceSet`. Unfortunately, Eclipse can only configure one Java version per Eclipse project. In this case, the enclosing Eclipse project is `com.ibm.wala.core`, and that project is configured to use Java 1.8. There's no way to tell Eclipse that just the `com.ibm.wala.core/src/test11Subjects` subdirectory should use Java 11. We might need to move the `com.ibm.wala.core/src/test11Subjects` material into a different Gradle subproject, and configure that project to use Java 11. I see that we do have a `com.ibm.wala.core.java11` Gradle subproject already, but it doesn't look like that subproject is configure to use Java 11. Is that subproject for code that operates on post-Java-1.8 features? Is the code *in* that subproject still expected to be written for Java 1.8, though?

The third problem involves a `class` that implements the troublesome `interface` that led to the first two errors. If we were using a Java 9+ compiler, then the first two problems would go away and this third error would vanish as well.

---

So the core of the problem is that we have Java 9+ code in an Eclipse project that is configured to use Java 1.8. That Eclipse project was, in turn, created from a Gradle subproject by Buildship. I believe that we'll either need to configure `com.ibm.wala.core` to use Java 9+ (which seems unlikely to be acceptable) or we'll have to move this Java 9+ code out into its own Gradle subproject, and configure *that* subproject to use Java 9+.

Hmm. @msridhar or @juliandolby, please check me on something. Is it necessary for `com.ibm.wala.core/src/test11Subjects/java/privateInterfaceMethods/PrivateInterface.java` to *compile* in order to serve its intended purpose as part of a test subject? Or would it be acceptable for this code to be present in *source* form but never be compiled to *bytecode*?

**Comment by msridhar** [comment] 2021-09-05 04:51
Thanks for the investigation @liblit!

> I see that we do have a `com.ibm.wala.core.java11` Gradle subproject already, but it doesn't look like that subproject is configure to use Java 11. Is that subproject for code that operates on post-Java-1.8 features? Is the code _in_ that subproject still expected to be written for Java 1.8, though?

I spoke with @juliandolby and the status of `com.ibm.wala.core.java11` is in flux.  It was intended for WALA-related code that must compile with Java 11+, but currently there is no code in that project that requires that.

> Hmm. @msridhar or @juliandolby, please check me on something. Is it necessary for `com.ibm.wala.core/src/test11Subjects/java/privateInterfaceMethods/PrivateInterface.java` to _compile_ in order to serve its intended purpose as part of a test subject? Or would it be acceptable for this code to be present in _source_ form but never be compiled to _bytecode_?

Unfortunately it is necessary for this code to be compiled to bytecode.  These are test programs for the Java bytecode frontend, to see that it supports Java 9+ features.  The `test11Subjects` source files get compiled and placed in a jar for analysis in a similar manner to the `testSubjects` source files.  See the changes in #912 

It's a bit annoying to need to create a new module just to support Eclipse, but I am ok with it if that's the best solution.  We could maybe stick the relevant test subjects and the corresponding JUnit tests in `com.ibm.wala.core.java11` since it happens to be there already.

**Comment by liblit** [comment] 2021-09-05 16:59
@msridhar wrote:
> It's a bit annoying to need to create a new module just to support Eclipse, but I am ok with it if that's the best solution.

Agreed. This is an interesting difference between Eclipse and IntelliJ IDEA:

* Eclipse + Buildship
  * Each Gradle project or subproject becomes an Eclipse project.
  * Each Eclipse project can have its own Java compiler version, classpath, etc.
* IntelliJ IDEA + JetBrains Gradle plugin
  * Each Gradle project, subproject, **or `sourceSet`** becomes an IntelliJ IDEA module
  * Each IntelliJ IDEA module can have its own Java compiler version, classpath, etc.

There's just no getting around the fact that Eclipse's JDK knobs are simply more coarse-grained than IntelliJ IDEA's knobs.

> We could maybe stick the relevant test subjects and the corresponding JUnit tests in `com.ibm.wala.core.java11` since it happens to be there already.

I'll give that a try and see how it goes.

**Comment by bowenshen** [comment] 2021-09-06 05:55
Based on your discussion, I tried to import the project into IntelliJ IDEA to see whether it's feasible solution. I'm using IntelliJ IDEA 2021.2.1(Community Edition).
Unfortunately, I still get some errors.
Execution failed for task ':com.ibm.wala.cast:test'.
> Could not resolve all files for configuration ':com.ibm.wala.cast:testRuntimeClasspath'.
   > Resolved 'org.apache.ant:ant:1.10.11' which is not part of the dependency lock state
   > Resolved 'org.apache.ant:ant-launcher:1.10.11' which is not part of the dependency lock state

I checked the project level of SDK is Java 1.8.0_101. I tested with Java 11 and had more errors.
Execution failed for task ':com.ibm.wala.cast.java.test.data:test'.
> Could not resolve all files for configuration ':com.ibm.wala.cast.java.test.data:testRuntimeClasspath'.
   > Resolved 'org.apache.ant:ant:1.10.11' which is not part of the dependency lock state
   > Resolved 'junit:junit:4.13.2' which is not part of the dependency lock state
   > Resolved 'org.apache.ant:ant-launcher:1.10.11' which is not part of the dependency lock state
   > Resolved 'org.hamcrest:hamcrest-core:1.3' which is not part of the dependency lock state

Is it something related gradle setting or IntelliJ setting?

**Comment by liblit** [comment] 2021-09-06 13:06
@bowenshen, I ran into similar "not part of the dependency lock state" problems while working on your original Eclipse import issue. Regardless of the cause, though, these new problems are clearly *not* related to Eclipse import, since Eclipse isn't even involved. Can I ask you to please create a new GiHub issue for these new problems? Otherwise, the current issue just diffuses into a general "@bowenshen tech support" tracker, which isn't very useful.

**Comment by bowenshen** [comment] 2021-09-06 13:09
You're right. It's unrelated with this issue. I'm going to create a new issue. Thank you.

**Comment by liblit** [comment] 2021-09-06 13:11
Thanks, @bowenshen! I appreciate your bug reports, and I appreciate your patience as I chip away at the problems you are finding.

**Comment by liblit** [comment] 2021-09-06 18:06
@bowenshen: no need to file a new issue for https://github.com/wala/WALA/issues/937#issuecomment-913363643 at this point. The problem has just been fixed in #954.

If you find further problems that are unrelated to Eclipse import, though, new issues to track each would still be appreciated.

**Closed** 2021-09-09 02:42 UTC
Labels: ide
