### ISSUE TITLE
When I try to get the source file name, I get null.

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#974] opened 2021-09-15 14:46 UTC
I want to get the source file name from the class file, and I use the instruction: `method.getDeclaringClass().getSourceFileName()` to get it. And I and the class file directory and java file directory to the scope.txt file. But I just get null. So how can I get the source file name from the method `getSourceFileName()`?
Thank you for answering my question！！
```java
package com.kwai.kguard.analysis;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;

import com.ibm.wala.cast.loader.AstClass;
import com.ibm.wala.classLoader.*;
import com.ibm.wala.ipa.callgraph.cha.CHACallGraph;
import com.ibm.wala.ipa.callgraph.impl.*;
import com.ibm.wala.ssa.SSAInstruction;
import com.ibm.wala.ssa.SSANewInstruction;
import com.ibm.wala.util.CancelException;
import com.kwai.kguard.util.ExcludeUtils;
import com.ibm.wala.ipa.callgraph.*;
import com.ibm.wala.ipa.cha.ClassHierarchyException;
import com.ibm.wala.ipa.cha.ClassHierarchyFactory;
import com.ibm.wala.ipa.cha.IClassHierarchy;
import com.ibm.wala.shrikeCT.InvalidClassFileException;
import com.ibm.wala.types.ClassLoaderReference;
import com.ibm.wala.types.TypeReference;
import com.ibm.wala.util.config.AnalysisScopeReader;
import com.ibm.wala.util.strings.StringStuff;
import com.ibm.wala.util.warnings.Warnings;
import com.kwai.kguard.wala.KwaiCallGraph;

/**
 * Driver that constructs a call graph for an application specified via a scope file.
 * Useful for getting some code to copy-paste.
 */
public class BuildSSA {
    public static void main(String[] args) throws IOException, ClassHierarchyException, IllegalArgumentException,
            CancelException, InvalidClassFileException, CancelException {
        long start = System.currentTimeMillis();

        String scopeFile = "scope.txt";

        AnalysisScope scope = AnalysisScopeReader.readJavaScope(scopeFile, null, com.ibm.wala.examples.drivers.ScopeFileCallGraph.class.getClassLoader());
        ExcludeUtils.addDefaultExclusions(scope);
        IClassHierarchy cha = ClassHierarchyFactory.makeWithRoot(scope);
        System.out.println(cha.getNumberOfClasses() + " classes");
        Warnings.clear();
        Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
        AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
        AnalysisCache cache = new AnalysisCacheImpl();
        CHACallGraph cg = new KwaiCallGraph(cha);
        cg.init(entrypoints);
        System.out.println("building call graph...");
        int i = 0;
        for (CGNode node : cg) {
            if (node.getIR() == null) {
                continue;
            }
            if (node.getMethod() instanceof ShrikeBTMethod) {
                ShrikeBTMethod method = (ShrikeBTMethod) node.getMethod();
                if ("Application".equals(method.getDeclaringClass().getClassLoader().toString())) {
                    String classInnerName = method.getDeclaringClass().getName().toString();
                    String signature = method.getSignature();
                    System.out.println(method.getDeclaringClass().getSourceFileName());
                }
            }
        }
        long end = System.currentTimeMillis();
        System.out.println("done");
        System.out.println("took " + (end - start) + "ms");
        System.out.println(CallGraphStats.getStats(cg));
    }
    private static Iterable<Entrypoint> makePublicEntrypoints(AnalysisScope scope, IClassHierarchy cha, String entryClass) {
        Collection<Entrypoint> result = new ArrayList<Entrypoint>();
        IClass klass = cha.lookupClass(TypeReference.findOrCreate(ClassLoaderReference.Application,
                StringStuff.deployment2CanonicalTypeString(entryClass)));
        for (IMethod m : klass.getDeclaredMethods()) {
            if (m.isPublic()) {
                result.add(new DefaultEntrypoint(m, cha));
            }
        }
        return result;
    }
}

```

**Comment by msridhar** [comment] 2021-09-16 15:23
@Anditty FYI I am looking into this.  This functionality has been stable for quite some time, but I realized yesterday that our regression tests for the source file name stuff have not been running on CI, so it's possibly something got broken.  It may take me a few days to investigate.

**Comment by Anditty** [comment] 2021-09-16 16:47
Thanks for your answer! Appreciate you being able to help with this! Very much looking forward to having a good result soon! Thanks a lot!

**Comment by Anditty** [comment] 2021-10-15 09:29
Has there been any progress on this issue please?

**Comment by Anditty** [comment] 2021-11-23 13:13
Thanks for a lot!

**Comment by msridhar** [comment] 2021-11-26 20:43
@Anditty very sorry for being slow on this.  Before I dig further, can you share your scope file?  And if you have a relative path to the source files, are you sure that you are running WALA from the correct working directory?

**Comment by msridhar** [comment] 2021-11-27 00:59
I fixed the regression tests in #1064 and the existing code seems to be working as intended.  @Anditty with some more details we can hopefully figure out what's going wrong in your setting

**Comment by Anditty** [comment] 2021-11-29 03:59
Thanks for your reply!
This is my scope.txt:
```
Primordial,Java,stdlib,none
Application,Java,sourceFile,Tmp.java
Application,Java,classFile,Tmp.class
```
And this is the content:
```java
public class Tmp {
    public static void main(String[] args) {
        System.err.println("hello wala!");
    }
}
```
And my wala version is 1.5.7, if there is a Updated version of wala, please tell me how to get it ~ 
Thanks! @msridhar

**Comment by msridhar** [comment] 2021-11-29 05:24
I am not sure why the class file would be seen in the scope but not the source file.  Here is the scope file we use for testing:

https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/test/resources/hello.txt

Only difference I see is that the classFile entry comes before the sourceFile entry.  Can you switch them and see if that makes a difference?

**Comment by Anditty** [comment] 2021-11-29 06:30
Thank you very much, after swapping the location it did solve the problem, but it seems that only the file name is output, I would like to know if there is a way to output the path of the file?

**Comment by msridhar** [comment] 2021-11-29 15:41
@Anditty that is not supported directly, you'll need to add absolute paths to the scope file and then that should work.  Alternately, you can just join append the source file name returned by WALA to the current working directory, since that's where it is resolved from.

**Comment by msridhar** [comment] 2021-11-29 16:46
I've updated the analysis scope documentation [here](https://github.com/wala/WALA/wiki/Analysis-Scope); closing this issue

**Closed by msridhar** 2021-11-29 16:46 UTC

**Comment by Anditty** [comment] 2021-11-29 18:30
Another problem here is that for internal classes, wala still returns null.

**Comment by Anditty** [comment] 2021-11-29 18:31
Another problem here is that for inner classes like `classA$classB`, wala still returns null
